### ISSUE TITLE
Update requirements.txt

### ISSUE THREAD

**Issue by LuckyMD** [jinhongjung/pyrwr#2]
Hi,

I see that you hardcoded the package versions for requirements.txt. Have you tested on newer versions? I cannot downgrade to the package versions you suggest in my environment. It would be good to have compatibility with the latest versions of numpy and scipy.

**Comment by jinhongjung** [comment]
Thank you for the comment. I will test this repo with the latest version of numpy ASAP. 
In the meantime, you might run this code with your numpy because numpy operations used in this repo are pretty simple, and expected to be run regardless of its version (maybe.. if it's wrong, I will fix it).
