### ISSUE TITLE
Inclusion of SimRank, SimRank, VertexSim, RoleSim, PageSim

### ISSUE THREAD

**Issue by BradKML** [jinhongjung/pyrwr#7]
As noted in https://github.com/abhishekmaha23/RoleSim-Python/issues/2 there are other Link predictions out there, and this repo seemed to have some of the best algorithms. Is it possible to include them in this repo?

**Comment by jinhongjung** [comment]
Sorry for the late reply. I think it is out of the scope of this repository. You may use our codes to implement other node similarity measures since most of them are calculated by power iteration.
