### ISSUE TITLE
Does the input file of the undirected graph need to have reverse edges？

### ISSUE THREAD

**Issue by fengxu1996** [jinhongjung/pyrwr#9]
Does the input file of the undirected graph need to have reverse edges?
like，
        0-1
        1-0

**Comment by jinhongjung** [comment]
Nope. Please remove one of the edges not to make edges redundant. pyrwr automatically adds the reverse edge. So, (0, 1) is enough for an unweighted and undirected graph. 

For that, it assumes src_id <= dst_id for edge edge (srd_id, dst_id), which is achieved by https://github.com/jinhongjung/pyrwr/blob/89bafcfb598e861af1ef8ba970a86e068b1777c6/utils/reader.py#L49. 
See more details in https://github.com/jinhongjung/pyrwr/blob/89bafcfb598e861af1ef8ba970a86e068b1777c6/utils/reader.py.

**Comment by fengxu1996** [comment]
OK, Thank you for your reply.
